### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by harsha-20** [weningerleon/BraTS2018#2]
Would you please explain your folder structure in more detail.  My Folder structure is as below
This was the data, I downloaded from BRATS official website. I didn't make any changes.
brats2018 
      |___train
           |____HGG 
           |____LGG
      |___validation
           |____HGG
           |____LGG

When I run directories.py , I was getting "Brats dataset not found"

**Comment by weningerleon** [comment]
Hi harsha,

Sorry for the long delay.
Did you change the variable basedir, raw_dir_train/validate/test according to your location of the data?

**Comment by harsha-20** [comment]
Hi Leon,

This issue solved . Another issue raised. How  did you split the data into three separate folders. Did you manually put the images into three separate folders  or did you write any script to do that ?

Thanks.

**Comment by weningerleon** [comment]
Hi,

the brats data comes in three different sets: train, validate, test. 
The folder structure is accordingly.
