### ISSUE TITLE
Could you help me solve a code training problem?

### ISSUE THREAD

**Issue by MFHcool** [weningerleon/BraTS2018#4]
When I was training the first Unet model,a mistake has interrupted my training.This mistake is ValueError: cannot reshape array of size 2 into shape (1,1). I think it means that there are some problems with this sentence "acc, acc_cls, mean_iu, fwavacc = evaluate(predictions_all, gts_all, N)" in train1.py. I learned the code and found the root cause is the misc.py. But I do not know how to solve the problem with the sentence "**hist = np.bincount(
        num_classes * label_true[mask].astype(int) +
        label_pred[mask], minlength=num_classes ** 2).reshape(num_classes, num_classes)**"

If you can help me,I'll be very grateful to you.
Best wishes!

**Comment by zhenxing123** [comment]
你好，我想问一下，对于数据的预处理是如何进行的？可以帮我一下吗？
